version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: php-fpm
    command: bash -c "curl -sL https://deb.nodesource.com/setup_18.x | bash - && apt-get install -y nodejs && php-fpm"
    volumes:
      - ./back/:/app
      - ./logs/php-error.log:/var/log/error.log
      - ./logs/php-access.log:/var/log/access.log
    networks:
      - bridge
  
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    image: node
    ports:
      - "3000:3000"
    volumes:
      - ./front:/node:cached
      - ./front/node_modules:/node/node_modules
    command: ./entrypoint.sh
    networks:
      - bridge
  
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8080:80
      - 5174:5173
    volumes:
      - ./back/:/app
    depends_on:
      - app
    image: nginx
    networks:
      - bridge

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_development
      MYSQL_USER: db-user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - bridge

networks:
  bridge:
    driver: bridge

volumes:
  mysql-volume:
